# Generated by Django 3.1 on 2021-01-09 16:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('fax', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('smtpserver', models.CharField(blank=True, max_length=225)),
                ('smtpemail', models.CharField(blank=True, max_length=225)),
                ('smtppassword', models.CharField(blank=True, max_length=225)),
                ('smtpport', models.CharField(blank=True, max_length=225)),
                ('icon', models.ImageField(blank=True, upload_to='images')),
                ('facebook', models.CharField(blank=True, max_length=225)),
                ('instagram', models.CharField(blank=True, max_length=225)),
                ('twitter', models.CharField(blank=True, max_length=225)),
                ('status', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=225)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 1, 9, 16, 18, 49, 589201, tzinfo=utc), verbose_name='date_created')),
            ],
        ),
    ]
