# Generated by Django 3.1 on 2021-01-14 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='seller',
        ),
    ]
