# Generated by Django 3.1 on 2021-01-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='varient',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='varient',
            name='orignal_price',
            field=models.FloatField(default=0),
        ),
    ]
