# Generated by Django 3.1 on 2021-01-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20210110_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='varient',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
