# Generated by Django 3.1 on 2021-01-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_clothing',
            new_name='is_buttomwear',
        ),
        migrations.AddField(
            model_name='product',
            name='Distressed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_topwear',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='wearable_Faded',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wearable_Rise',
            field=models.TextField(blank=True, null=True),
        ),
    ]
